// This file is @generated by prost-build.
///
/// The 64-bit integer feature type.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Int64FeatureType {}
///
/// The double-precision floating point number feature type.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DoubleFeatureType {}
///
/// The string feature type.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StringFeatureType {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SizeRange {
    #[prost(uint64, tag = "1")]
    pub lower_bound: u64,
    /// negative value means unbound otherwise upperbound is included in range
    #[prost(int64, tag = "2")]
    pub upper_bound: i64,
}
///
/// The image feature type.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImageFeatureType {
    #[prost(int64, tag = "1")]
    pub width: i64,
    #[prost(int64, tag = "2")]
    pub height: i64,
    #[prost(enumeration = "image_feature_type::ColorSpace", tag = "3")]
    pub color_space: i32,
    #[prost(oneof = "image_feature_type::SizeFlexibility", tags = "21, 31")]
    pub size_flexibility: ::core::option::Option<image_feature_type::SizeFlexibility>,
}
/// Nested message and enum types in `ImageFeatureType`.
pub mod image_feature_type {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ImageSize {
        #[prost(uint64, tag = "1")]
        pub width: u64,
        #[prost(uint64, tag = "2")]
        pub height: u64,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct EnumeratedImageSizes {
        #[prost(message, repeated, tag = "1")]
        pub sizes: ::prost::alloc::vec::Vec<ImageSize>,
    }
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ImageSizeRange {
        #[prost(message, optional, tag = "1")]
        pub width_range: ::core::option::Option<super::SizeRange>,
        #[prost(message, optional, tag = "2")]
        pub height_range: ::core::option::Option<super::SizeRange>,
    }
    /// Assumes raw (decompressed) format
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ColorSpace {
        InvalidColorSpace = 0,
        ///   8 bits per pixel
        Grayscale = 10,
        /// 32 bits per pixel: RGBA with A channel ignored
        Rgb = 20,
        /// 32 bits per pixel: BGRA with A channel ignored
        Bgr = 30,
        /// 16 bits float per pixel
        GrayscaleFloat16 = 40,
    }
    impl ColorSpace {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::InvalidColorSpace => "INVALID_COLOR_SPACE",
                Self::Grayscale => "GRAYSCALE",
                Self::Rgb => "RGB",
                Self::Bgr => "BGR",
                Self::GrayscaleFloat16 => "GRAYSCALE_FLOAT16",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "INVALID_COLOR_SPACE" => Some(Self::InvalidColorSpace),
                "GRAYSCALE" => Some(Self::Grayscale),
                "RGB" => Some(Self::Rgb),
                "BGR" => Some(Self::Bgr),
                "GRAYSCALE_FLOAT16" => Some(Self::GrayscaleFloat16),
                _ => None,
            }
        }
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum SizeFlexibility {
        #[prost(message, tag = "21")]
        EnumeratedSizes(EnumeratedImageSizes),
        #[prost(message, tag = "31")]
        ImageSizeRange(ImageSizeRange),
    }
}
///
/// The array feature type.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ArrayFeatureType {
    #[prost(int64, repeated, tag = "1")]
    pub shape: ::prost::alloc::vec::Vec<i64>,
    #[prost(enumeration = "array_feature_type::ArrayDataType", tag = "2")]
    pub data_type: i32,
    #[prost(oneof = "array_feature_type::ShapeFlexibility", tags = "21, 31")]
    pub shape_flexibility: ::core::option::Option<array_feature_type::ShapeFlexibility>,
    #[prost(oneof = "array_feature_type::DefaultOptionalValue", tags = "41, 51, 61")]
    pub default_optional_value: ::core::option::Option<
        array_feature_type::DefaultOptionalValue,
    >,
}
/// Nested message and enum types in `ArrayFeatureType`.
pub mod array_feature_type {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Shape {
        #[prost(int64, repeated, tag = "1")]
        pub shape: ::prost::alloc::vec::Vec<i64>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct EnumeratedShapes {
        #[prost(message, repeated, tag = "1")]
        pub shapes: ::prost::alloc::vec::Vec<Shape>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ShapeRange {
        /// sizeRanges.size() must be length 1 or 3
        /// sizeRanges\[d\] specifies the allowed range for dimension d
        #[prost(message, repeated, tag = "1")]
        pub size_ranges: ::prost::alloc::vec::Vec<super::SizeRange>,
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ArrayDataType {
        InvalidArrayDataType = 0,
        /// 0x10000 | 32
        Float32 = 65568,
        /// 0x10000 | 64
        Double = 65600,
        /// 0x20000 | 32
        Int32 = 131104,
        /// 0x20000 |  8
        Int8 = 131080,
        /// 0x10000 | 16
        Float16 = 65552,
    }
    impl ArrayDataType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::InvalidArrayDataType => "INVALID_ARRAY_DATA_TYPE",
                Self::Float32 => "FLOAT32",
                Self::Double => "DOUBLE",
                Self::Int32 => "INT32",
                Self::Int8 => "INT8",
                Self::Float16 => "FLOAT16",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "INVALID_ARRAY_DATA_TYPE" => Some(Self::InvalidArrayDataType),
                "FLOAT32" => Some(Self::Float32),
                "DOUBLE" => Some(Self::Double),
                "INT32" => Some(Self::Int32),
                "INT8" => Some(Self::Int8),
                "FLOAT16" => Some(Self::Float16),
                _ => None,
            }
        }
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ShapeFlexibility {
        #[prost(message, tag = "21")]
        EnumeratedShapes(EnumeratedShapes),
        #[prost(message, tag = "31")]
        ShapeRange(ShapeRange),
    }
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum DefaultOptionalValue {
        #[prost(int32, tag = "41")]
        IntDefaultValue(i32),
        #[prost(float, tag = "51")]
        FloatDefaultValue(f32),
        #[prost(double, tag = "61")]
        DoubleDefaultValue(f64),
    }
}
///
/// The dictionary feature type.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DictionaryFeatureType {
    ///
    ///   Key/value type tags, with the following restrictions:
    ///   - ``keyType`` must be a hashable type
    ///   - ``valueType`` is assumed to be a ``double``
    #[prost(oneof = "dictionary_feature_type::KeyType", tags = "1, 2")]
    pub key_type: ::core::option::Option<dictionary_feature_type::KeyType>,
}
/// Nested message and enum types in `DictionaryFeatureType`.
pub mod dictionary_feature_type {
    ///
    ///   Key/value type tags, with the following restrictions:
    ///   - ``keyType`` must be a hashable type
    ///   - ``valueType`` is assumed to be a ``double``
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum KeyType {
        #[prost(message, tag = "1")]
        Int64KeyType(super::Int64FeatureType),
        #[prost(message, tag = "2")]
        StringKeyType(super::StringFeatureType),
    }
}
///
/// The Sequence feature type.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SequenceFeatureType {
    /// Range of allowed size/length/count of sequence
    #[prost(message, optional, tag = "101")]
    pub size_range: ::core::option::Option<SizeRange>,
    ///
    /// Currently only categorical int64 and String sequences are supported
    #[prost(oneof = "sequence_feature_type::Type", tags = "1, 3")]
    pub r#type: ::core::option::Option<sequence_feature_type::Type>,
}
/// Nested message and enum types in `SequenceFeatureType`.
pub mod sequence_feature_type {
    ///
    /// Currently only categorical int64 and String sequences are supported
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Type {
        #[prost(message, tag = "1")]
        Int64Type(super::Int64FeatureType),
        #[prost(message, tag = "3")]
        StringType(super::StringFeatureType),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateFeatureType {
    #[prost(oneof = "state_feature_type::Type", tags = "1")]
    pub r#type: ::core::option::Option<state_feature_type::Type>,
}
/// Nested message and enum types in `StateFeatureType`.
pub mod state_feature_type {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Type {
        #[prost(message, tag = "1")]
        ArrayType(super::ArrayFeatureType),
    }
}
///
/// A feature, which may be optional.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureType {
    #[prost(bool, tag = "1000")]
    pub is_optional: bool,
    #[prost(oneof = "feature_type::Type", tags = "1, 2, 3, 4, 5, 6, 7, 8")]
    pub r#type: ::core::option::Option<feature_type::Type>,
}
/// Nested message and enum types in `FeatureType`.
pub mod feature_type {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Type {
        #[prost(message, tag = "1")]
        Int64Type(super::Int64FeatureType),
        #[prost(message, tag = "2")]
        DoubleType(super::DoubleFeatureType),
        #[prost(message, tag = "3")]
        StringType(super::StringFeatureType),
        #[prost(message, tag = "4")]
        ImageType(super::ImageFeatureType),
        #[prost(message, tag = "5")]
        MultiArrayType(super::ArrayFeatureType),
        #[prost(message, tag = "6")]
        DictionaryType(super::DictionaryFeatureType),
        #[prost(message, tag = "7")]
        SequenceType(super::SequenceFeatureType),
        #[prost(message, tag = "8")]
        StateType(super::StateFeatureType),
    }
}
///
/// A pipeline consists of one or more models.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pipeline {
    #[prost(message, repeated, tag = "1")]
    pub models: ::prost::alloc::vec::Vec<Model>,
    /// Optional names given for each model
    /// If not supplied it defaults to \["model0",..., "model"(models.size()-1)\]
    /// These names can be used to disambiguate the scope / domain of a parameter
    #[prost(string, repeated, tag = "2")]
    pub names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
///
/// A classifier pipeline.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PipelineClassifier {
    #[prost(message, optional, tag = "1")]
    pub pipeline: ::core::option::Option<Pipeline>,
}
///
/// A regressor pipeline.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PipelineRegressor {
    #[prost(message, optional, tag = "1")]
    pub pipeline: ::core::option::Option<Pipeline>,
}
///
/// A feature description
/// consisting of a name, short description, and type.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureDescription {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub short_description: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub r#type: ::core::option::Option<FeatureType>,
}
///
/// Model metadata,
/// consisting of a short description, a version string,
/// an author, a license, and any other user defined
/// key/value meta data.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Metadata {
    #[prost(string, tag = "1")]
    pub short_description: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version_string: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub author: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub license: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "100")]
    pub user_defined: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
///
/// A description of a function.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionDescription {
    /// The function name.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Input feature descriptions for the function.
    #[prost(message, repeated, tag = "2")]
    pub input: ::prost::alloc::vec::Vec<FeatureDescription>,
    /// Output feature descriptions for the function.
    #[prost(message, repeated, tag = "3")]
    pub output: ::prost::alloc::vec::Vec<FeatureDescription>,
    /// State feature descriptions for the function.
    ///
    /// The `type` of each feature description must be `StateFeatureType`.
    #[prost(message, repeated, tag = "6")]
    pub state: ::prost::alloc::vec::Vec<FeatureDescription>,
    /// \[Required for regressor and classifier functions\]: the name
    /// to give to an output feature containing the prediction.
    #[prost(string, tag = "4")]
    pub predicted_feature_name: ::prost::alloc::string::String,
    /// \[Optional for classifier functions\]: the name to give to an
    /// output feature containing a dictionary mapping class
    /// labels to their predicted probabilities. If not specified,
    /// the dictionary will not be returned by the model.
    #[prost(string, tag = "5")]
    pub predicted_probabilities_name: ::prost::alloc::string::String,
}
///
/// A description of a model,
/// consisting of descriptions of its input and output features.
/// Both regressor and classifier models require the name of the
/// primary predicted output feature (``predictedFeatureName``).
/// Classifier models can specify the output feature containing
/// probabilities for the predicted classes
/// (``predictedProbabilitiesName``).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelDescription {
    /// Functions in the model.
    ///
    /// Some model types (e.g. ML Program) support multiple functions. For
    /// example, a large language model might have "prompt" and "extend"
    /// functions. Each has a different input and output behavior, but
    /// they are in a same model and share resources.
    ///
    /// If the model has more than one function, use the multiple
    /// function configuration and declare the feature descriptions and
    /// associated properties at function level.
    ///
    /// If the model type doesn't support multiple functions or the
    /// model has just "main" function, declare the feature
    /// descriptions and associated properties at the model level.
    ///
    /// Note: feature descriptions and associated properties mentioned
    /// above include input, output, state, predictedFeatureName,
    /// predictedProbabilitiesName, and trainingInput fields.
    #[prost(message, repeated, tag = "20")]
    pub functions: ::prost::alloc::vec::Vec<FunctionDescription>,
    /// The default function.
    ///
    /// The default function is the one that is automatically used when
    /// one doesn't explicitly specify.
    ///
    /// The value must be one of the names in `functions` message
    /// above. If `functions` is empty, this field must not be present.
    #[prost(string, tag = "21")]
    pub default_function_name: ::prost::alloc::string::String,
    /// The metadata (e.g. author, licence, etc) of the model.
    #[prost(message, optional, tag = "100")]
    pub metadata: ::core::option::Option<Metadata>,
    #[prost(message, repeated, tag = "1")]
    pub input: ::prost::alloc::vec::Vec<FeatureDescription>,
    #[prost(message, repeated, tag = "10")]
    pub output: ::prost::alloc::vec::Vec<FeatureDescription>,
    /// State feature descriptions for the function.
    ///
    /// The `type` of each feature description must be `StateFeatureType`.
    #[prost(message, repeated, tag = "13")]
    pub state: ::prost::alloc::vec::Vec<FeatureDescription>,
    /// \[Required for regressor and classifier models\]: the name
    /// to give to an output feature containing the prediction.
    #[prost(string, tag = "11")]
    pub predicted_feature_name: ::prost::alloc::string::String,
    /// \[Optional for classifier models\]: the name to give to an
    /// output feature containing a dictionary mapping class
    /// labels to their predicted probabilities. If not specified,
    /// the dictionary will not be returned by the model.
    #[prost(string, tag = "12")]
    pub predicted_probabilities_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "50")]
    pub training_input: ::prost::alloc::vec::Vec<FeatureDescription>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SerializedModel {
    /// Identifier whose content describes the model type of the serialized protocol buffer message.
    #[prost(string, tag = "1")]
    pub identifier: ::prost::alloc::string::String,
    /// Must be a valid serialized protocol buffer of the above specified type.
    #[prost(bytes = "vec", tag = "2")]
    pub model: ::prost::alloc::vec::Vec<u8>,
}
///
/// A Core ML model,
/// consisting of a specification version,
/// a model description, and a model type.
///
/// Core ML model compatibility is indicated by
/// a monotonically increasing specification version number,
/// which is incremented anytime a backward-incompatible change is made
/// (this is functionally equivalent to the MAJOR version number
/// described by `Semantic Versioning 2.0.0 <<http://semver.org/>`_>).
///
/// Specification Versions : OS Availability (Core ML Version)
///
/// 1 : iOS 11, macOS 10.13, tvOS 11, watchOS 4 (Core ML 1)
/// - Feedforward & Recurrent Neural Networks
/// - General Linear Models
/// - Tree Ensembles
/// - Support Vector Machines
/// - Pipelines
/// - Feature Engineering
///
/// 2 : iOS 11.2, macOS 10.13.2, tvOS 11.2, watchOS 4.2 (Core ML 1.2)
/// - Custom Layers for Neural Networks
/// - Float 16 support for Neural Network layers
///
/// 3 : iOS 12, macOS 10.14, tvOS 12, watchOS 5 (Core ML 2)
/// - Flexible shapes and image sizes
/// - Categorical sequences
/// - Core ML Vision Feature Print, Text Classifier, Word Tagger
/// - Non Max Suppression
/// - Crop and Resize Bilinear NN layers
/// - Custom Models
///
/// 4 : iOS 13, macOS 10.15, tvOS 13, watchOS 6 (Core ML 3)
/// - Updatable models
/// - Exact shape / general rank mapping for neural networks
/// - Large expansion of supported neural network layers
///    - Generalized operations
///    - Control flow
///    - Dynamic layers
///    - See NeuralNetwork.proto
/// - Nearest Neighbor Classifier
/// - Sound Analysis Prepreocessing
/// - Recommender
/// - Linked Model
/// - NLP Gazeteer
/// - NLP WordEmbedding
///
/// 5 : iOS 14, macOS 11, tvOS 14, watchOS 7 (Core ML 4)
/// - Model Deployment
/// - Model Encryption
/// - Unified converter API with PyTorch and Tensorflow 2 Support in coremltools 4
/// - MIL builder for neural networks and composite ops in coremltools 4
/// - New layers in neural network:
///       - CumSum
///       - OneHot
///       - ClampedReLu
///       - ArgSort
///       - SliceBySize
///       - Convolution3D
///       - Pool3D
///       - Bilinear Upsample with align corners and fractional factors
///       - PixelShuffle
///       - MatMul with int8 weights and int8 activations
///       - Concat interleave
///       - See NeuralNetwork.proto
/// - Enhanced Xcode model view with interactive previews
/// - Enhanced Xcode Playground support for Core ML models
///
/// 6 : iOS 15, macOS 12, tvOS 15, watchOS 8 (Core ML 5)
/// - Core ML Audio Feature Print
/// - new type of model: mlprogram (MILSpec.Program)
///
/// 7 : iOS 16, macOS 13, tvOS 16, watchOS 9 (Core ML 6)
/// - FLOAT16 array data type
/// - GRAYSCALE_FLOAT16 image color space.
///
/// 8 : iOS 17, macOS 14, tvOS 17, watchOS 10 (Core ML 7)
/// - iOS 17 ops
/// - Scene print v2
/// - ClassConfidenceThresholding model
///
/// 9 : iOS 18, macOS 15, tvOS 18, watchOS 11 (Core ML 8)
/// - multiple functions
///
/// 10 : iOS 26, macOS 26, tvOS 26, watchOS 26, visionOS 26 (Core ML 9)
/// - Int8 MultiArray types for ML Programs
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Model {
    #[prost(int32, tag = "1")]
    pub specification_version: i32,
    #[prost(message, optional, tag = "2")]
    pub description: ::core::option::Option<ModelDescription>,
    ///
    /// Following model types support on-device update:
    ///
    /// - NeuralNetworkClassifier
    /// - NeuralNetworkRegressor
    /// - NeuralNetwork
    /// - KNearestNeighborsClassifier
    #[prost(bool, tag = "10")]
    pub is_updatable: bool,
    /// start at 200 here
    /// model specific parameters:
    #[prost(oneof = "model::Type", tags = "200, 201, 202, 502, 3000")]
    pub r#type: ::core::option::Option<model::Type>,
}
/// Nested message and enum types in `Model`.
pub mod model {
    /// start at 200 here
    /// model specific parameters:
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Type {
        /// pipeline starts at 200
        #[prost(message, tag = "200")]
        PipelineClassifier(super::PipelineClassifier),
        #[prost(message, tag = "201")]
        PipelineRegressor(super::PipelineRegressor),
        #[prost(message, tag = "202")]
        Pipeline(super::Pipeline),
        /// GLMRegressor glmRegressor = 300;
        /// SupportVectorRegressor supportVectorRegressor = 301;
        /// TreeEnsembleRegressor treeEnsembleRegressor = 302;
        /// NeuralNetworkRegressor neuralNetworkRegressor = 303;
        /// BayesianProbitRegressor bayesianProbitRegressor = 304;
        ///
        /// // classifiers start at 400
        /// GLMClassifier glmClassifier = 400;
        /// SupportVectorClassifier supportVectorClassifier = 401;
        /// TreeEnsembleClassifier treeEnsembleClassifier = 402;
        /// NeuralNetworkClassifier neuralNetworkClassifier = 403;
        /// KNearestNeighborsClassifier kNearestNeighborsClassifier = 404;
        ///
        /// // generic models start at 500
        /// NeuralNetwork neuralNetwork = 500;
        /// ItemSimilarityRecommender itemSimilarityRecommender = 501;
        #[prost(message, tag = "502")]
        MlProgram(super::mil_spec::Program),
        /// Reserved private messages start at 3000
        /// These messages are subject to change with no notice or support.
        #[prost(message, tag = "3000")]
        SerializedModel(super::SerializedModel),
    }
}
